"""intake openings applications and job queue

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 16:20:54.296528
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('applicant_email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('applicant_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('applicant_state', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('possible_duplicate_candidate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_applicant_email'), ['applicant_email'], unique=False)
        batch_op.create_foreign_key('fk_applications_possible_duplicate', 'candidates', ['possible_duplicate_candidate_id'], ['candidate_id'])

    with op.batch_alter_table('job_openings', schema=None) as batch_op:
        # Existing openings predate the choice of rule set; they were all created
        # under the UGC-only design, so GENERAL is what they meant.
        batch_op.add_column(sa.Column('discipline_group', sa.String(length=40), nullable=False, server_default='GENERAL'))
        batch_op.add_column(sa.Column('closing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_openings', schema=None) as batch_op:
        batch_op.drop_column('closed_at')
        batch_op.drop_column('closing_date')
        batch_op.drop_column('discipline_group')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_applications_possible_duplicate', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_applications_applicant_email'))
        batch_op.drop_column('possible_duplicate_candidate_id')
        batch_op.drop_column('applicant_state')
        batch_op.drop_column('applicant_phone')
        batch_op.drop_column('applicant_email')
        batch_op.drop_column('applicant_name')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_application_id'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
