"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 17:23:47.129892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('institutions_master',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=250), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('institution_name')
    )
    op.create_table('regulators',
    sa.Column('regulator_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('norms_document_ref', sa.String(length=300), nullable=True),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('regulator_id')
    )
    op.create_table('candidate_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('highlight_type', sa.String(length=40), nullable=False),
    sa.Column('source_reference', sa.String(length=80), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_highlights_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_personal_details',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('current_address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('differently_abled_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('candidate_profile',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('highest_qualification_id', sa.Integer(), nullable=True),
    sa.Column('resume_source', sa.String(length=20), nullable=False),
    sa.Column('raw_resume_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('candidate_research_profile',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('scopus_author_id', sa.String(length=40), nullable=True),
    sa.Column('orcid_id', sa.String(length=40), nullable=True),
    sa.Column('google_scholar_id', sa.String(length=80), nullable=True),
    sa.Column('total_citations', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('rule_versions',
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.String(length=20), nullable=False),
    sa.Column('instrument_name', sa.String(length=300), nullable=False),
    sa.Column('notification_no', sa.String(length=120), nullable=True),
    sa.Column('gazette_ref', sa.String(length=200), nullable=True),
    sa.Column('notified_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('superseded_on', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.regulator_id'], ),
    sa.PrimaryKeyConstraint('rule_version_id')
    )
    op.create_table('schools',
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('faculty', sa.String(length=120), nullable=False),
    sa.Column('regulator_id', sa.String(length=20), nullable=False),
    sa.Column('overlay_regulator_id', sa.String(length=20), nullable=True),
    sa.Column('is_hiring_unit', sa.Boolean(), nullable=False),
    sa.Column('has_departments', sa.Boolean(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=False),
    sa.Column('confirmation_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['overlay_regulator_id'], ['regulators.regulator_id'], ),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.regulator_id'], ),
    sa.PrimaryKeyConstraint('school_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('school_id', 'name')
    )
    op.create_table('recruitment_drives',
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('advertisement_ref', sa.String(length=80), nullable=True),
    sa.Column('advertisement_date', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('drive_id')
    )
    op.create_table('rubric_rules',
    sa.Column('rubric_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('min_years', sa.Float(), nullable=True),
    sa.Column('min_publications', sa.Integer(), nullable=True),
    sa.Column('requires_phd', sa.Boolean(), nullable=False),
    sa.Column('min_marks_pct', sa.Float(), nullable=True),
    sa.Column('research_score_threshold', sa.Float(), nullable=True),
    sa.Column('net_set_required', sa.Boolean(), nullable=False),
    sa.Column('authority_clause', sa.String(length=120), nullable=False),
    sa.Column('authority_page', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('rubric_rule_id'),
    sa.UniqueConstraint('rule_version_id', 'designation')
    )
    op.create_table('job_openings',
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['recruitment_drives.drive_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('opening_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('applied_designation', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('differently_abled', sa.Boolean(), nullable=True),
    sa.Column('study_leave_taken', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resume_source', sa.String(length=20), nullable=False),
    sa.Column('resume_filename', sa.String(length=255), nullable=False),
    sa.Column('resume_path', sa.String(length=500), nullable=False),
    sa.Column('resume_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['opening_id'], ['job_openings.opening_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_resume_sha256'), ['resume_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('candidate_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_achievements_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_achievements_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organiser', sa.String(length=300), nullable=True),
    sa.Column('duration_stated', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_events_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_experience',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('employer_name', sa.String(length=250), nullable=True),
    sa.Column('designation_held', sa.String(length=200), nullable=True),
    sa.Column('qualification_level_at_time', sa.String(length=10), nullable=True),
    sa.Column('discipline', sa.String(length=200), nullable=True),
    sa.Column('start_stated', sa.String(length=10), nullable=True),
    sa.Column('end_stated', sa.String(length=10), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('duration_stated', sa.String(length=80), nullable=True),
    sa.Column('experience_type', sa.String(length=20), nullable=False),
    sa.Column('concurrent_with_study', sa.Boolean(), nullable=True),
    sa.Column('study_leave_taken', sa.Boolean(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('experience_id')
    )
    with op.batch_alter_table('candidate_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_experience_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_experience_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_guidance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_guidance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_guidance_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_guidance_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(length=200), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_hobbies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_hobbies_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_hobbies_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership', sa.String(length=300), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_memberships_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_memberships_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_publications',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('publication_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('indexing', sa.String(length=80), nullable=True),
    sa.Column('venue_name', sa.String(length=400), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_first_author', sa.Boolean(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('publication_id')
    )
    with op.batch_alter_table('candidate_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_publications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_publications_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_qualifications',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('degree_level', sa.String(length=10), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('discipline', sa.String(length=200), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('college_name', sa.String(length=250), nullable=True),
    sa.Column('university_name', sa.String(length=250), nullable=True),
    sa.Column('year_of_completion', sa.Integer(), nullable=True),
    sa.Column('completion_stated', sa.String(length=10), nullable=True),
    sa.Column('marks_pct', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('division', sa.String(length=80), nullable=True),
    sa.Column('is_highest', sa.Boolean(), nullable=False),
    sa.Column('phd_status', sa.String(length=20), nullable=False),
    sa.Column('phd_regulation_year', sa.String(length=10), nullable=True),
    sa.Column('thesis_title', sa.String(length=500), nullable=True),
    sa.Column('guide', sa.String(length=200), nullable=True),
    sa.Column('registration_stated', sa.String(length=10), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions_master.institution_id'], ),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    with op.batch_alter_table('candidate_qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_qualifications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_qualifications_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_skills_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_skills_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_subjects_taught',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=250), nullable=False),
    sa.Column('course_level', sa.String(length=10), nullable=True),
    sa.Column('years_taught', sa.Float(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('found_in_resume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_subjects_taught', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_subjects_taught_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_subjects_taught_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('research_score', sa.Float(), nullable=True),
    sa.Column('adjusted_experience_years', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('eligible_designation', sa.String(length=40), nullable=True),
    sa.Column('was_recategorised', sa.Boolean(), nullable=False),
    sa.Column('failing_clause', sa.String(length=300), nullable=True),
    sa.Column('failing_clause_page', sa.String(length=40), nullable=True),
    sa.Column('rule_version_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_application_id'), ['application_id'], unique=False)

    op.create_table('extracted_data',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('highest_degree', sa.String(length=20), nullable=True),
    sa.Column('marks_pct', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('has_phd', sa.Boolean(), nullable=True),
    sa.Column('phd_status', sa.String(length=20), nullable=True),
    sa.Column('phd_award_date', sa.Date(), nullable=True),
    sa.Column('phd_award_date_precision', sa.String(length=10), nullable=True),
    sa.Column('phd_regulation', sa.String(length=10), nullable=True),
    sa.Column('masters_award_date', sa.Date(), nullable=True),
    sa.Column('masters_award_date_precision', sa.String(length=10), nullable=True),
    sa.Column('net_set_status', sa.String(length=10), nullable=True),
    sa.Column('set_state', sa.String(length=60), nullable=True),
    sa.Column('study_leave_taken', sa.Boolean(), nullable=True),
    sa.Column('teaching_years', sa.Float(), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('publications_in_progress_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('lighter_model_fallback', sa.Boolean(), nullable=False),
    sa.Column('raw_llm_output', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('state_transitions',
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=True),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('transition_id')
    )
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_transitions_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###

    # Added once both tables exist. Declared inside create_table it was
    # silently skipped on PostgreSQL, leaving the column with no constraint.
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_profile_highest_qual', 'candidate_qualifications',
            ['highest_qualification_id'], ['qualification_id'],
        )


def downgrade() -> None:
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profile_highest_qual', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_transitions_application_id'))

    op.drop_table('state_transitions')
    op.drop_table('extracted_data')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_application_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('candidate_subjects_taught', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_subjects_taught_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_subjects_taught_application_id'))

    op.drop_table('candidate_subjects_taught')
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_skills_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_skills_application_id'))

    op.drop_table('candidate_skills')
    with op.batch_alter_table('candidate_qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_qualifications_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_qualifications_application_id'))

    op.drop_table('candidate_qualifications')
    with op.batch_alter_table('candidate_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_publications_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_publications_application_id'))

    op.drop_table('candidate_publications')
    with op.batch_alter_table('candidate_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_memberships_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_memberships_application_id'))

    op.drop_table('candidate_memberships')
    with op.batch_alter_table('candidate_hobbies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_hobbies_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_hobbies_application_id'))

    op.drop_table('candidate_hobbies')
    with op.batch_alter_table('candidate_guidance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_guidance_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_guidance_application_id'))

    op.drop_table('candidate_guidance')
    with op.batch_alter_table('candidate_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_experience_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_experience_application_id'))

    op.drop_table('candidate_experience')
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_events_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_events_application_id'))

    op.drop_table('candidate_events')
    with op.batch_alter_table('candidate_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_achievements_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_achievements_application_id'))

    op.drop_table('candidate_achievements')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_resume_sha256'))

    op.drop_table('applications')
    op.drop_table('job_openings')
    op.drop_table('rubric_rules')
    op.drop_table('recruitment_drives')
    op.drop_table('departments')
    op.drop_table('schools')
    op.drop_table('rule_versions')
    op.drop_table('candidate_research_profile')
    op.drop_table('candidate_profile')
    op.drop_table('candidate_personal_details')
    with op.batch_alter_table('candidate_highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_highlights_candidate_id'))

    op.drop_table('candidate_highlights')
    op.drop_table('regulators')
    op.drop_table('institutions_master')
    op.drop_table('candidates')
    # ### end Alembic commands ###
