"""statutory rules as data

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 14:46:09.225277
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relaxation_rules',
    sa.Column('relaxation_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('relaxation_pct', sa.Float(), nullable=False),
    sa.Column('applies_to_levels', sa.JSON(), nullable=False),
    sa.Column('applies_to_categories', sa.JSON(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('authority_clause', sa.String(length=160), nullable=False),
    sa.Column('authority_page', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('relaxation_rule_id'),
    sa.UniqueConstraint('rule_version_id', 'code')
    )
    op.create_table('score_rules',
    sa.Column('score_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('table_code', sa.String(length=20), nullable=False),
    sa.Column('row_code', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('faculty_group', sa.String(length=10), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('band_min', sa.Float(), nullable=True),
    sa.Column('band_max', sa.Float(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=True),
    sa.Column('applies_to_categories', sa.JSON(), nullable=True),
    sa.Column('authority_page', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('score_rule_id'),
    sa.UniqueConstraint('table_code', 'row_code')
    )
    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_rules_table_code'), ['table_code'], unique=False)

    # rubric_rules is rebuilt, not altered. Its unique constraint was created
    # without a name in 0001, so PostgreSQL and SQLite know it by different
    # names (or none) and it cannot be dropped the same way on both. The table
    # holds only rules loaded by `python -m backend.rules_seed`, which reloads
    # them, and nothing references it.
    op.drop_table('rubric_rules')
    op.create_table('rubric_rules',
    sa.Column('rubric_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('discipline_group', sa.String(length=40), nullable=False),
    sa.Column('min_years', sa.Float(), nullable=True),
    sa.Column('min_publications', sa.Integer(), nullable=True),
    sa.Column('requires_phd', sa.Boolean(), nullable=False),
    sa.Column('min_marks_pct', sa.Float(), nullable=True),
    sa.Column('research_score_threshold', sa.Float(), nullable=True),
    sa.Column('net_set_required', sa.Boolean(), nullable=False),
    sa.Column('min_doctoral_guided', sa.Integer(), nullable=True),
    sa.Column('authority_clause', sa.String(length=160), nullable=False),
    sa.Column('authority_page', sa.String(length=60), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('rubric_rule_id'),
    sa.UniqueConstraint('rule_version_id', 'designation', 'discipline_group', name='uq_rubric_rules_version_designation_group')
    )

    # `code` is added in three steps so the migration also works on a
    # database that already has rule_versions rows: a NOT NULL column cannot
    # be added to a non-empty table. Existing rows get a placeholder code.
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('source_sha256', sa.String(length=64), nullable=True))
    op.execute("UPDATE rule_versions SET code = 'LEGACY-' || CAST(rule_version_id AS VARCHAR(20)) WHERE code IS NULL")
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.alter_column('code', existing_type=sa.String(length=40), nullable=False)
        batch_op.create_unique_constraint('uq_rule_versions_code', ['code'])
        # The AICTE regulation's own title is longer than 300 characters.
        batch_op.alter_column('instrument_name', existing_type=sa.String(length=300),
                              type_=sa.String(length=500), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rule_versions_code', type_='unique')
        batch_op.alter_column('instrument_name', existing_type=sa.String(length=500),
                              type_=sa.String(length=300), existing_nullable=False,
                              postgresql_using='left(instrument_name, 300)')
        batch_op.drop_column('source_sha256')
        batch_op.drop_column('source_url')
        batch_op.drop_column('code')

    op.drop_table('rubric_rules')
    op.create_table('rubric_rules',
    sa.Column('rubric_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('min_years', sa.Float(), nullable=True),
    sa.Column('min_publications', sa.Integer(), nullable=True),
    sa.Column('requires_phd', sa.Boolean(), nullable=False),
    sa.Column('min_marks_pct', sa.Float(), nullable=True),
    sa.Column('research_score_threshold', sa.Float(), nullable=True),
    sa.Column('net_set_required', sa.Boolean(), nullable=False),
    sa.Column('authority_clause', sa.String(length=120), nullable=False),
    sa.Column('authority_page', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('rubric_rule_id'),
    sa.UniqueConstraint('rule_version_id', 'designation')
    )

    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_rules_table_code'))

    op.drop_table('score_rules')
    op.drop_table('relaxation_rules')
    # ### end Alembic commands ###
